worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout 65;

    server {
        listen 80;

        server_name localhost;
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri /index.html;
        }

        location /avatars/ {
            alias /uploads/avatars/;
            autoindex off;
            add_header Cache-Control no-cache;
        }

        location /product_photos/ {
            alias /product_photos/;
            autoindex off;
            add_header Cache-Control no-cache;
        }

        location /users/ {
            proxy_pass http://lab1_2_users_service:3002/users/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /products/ {
            proxy_pass http://lab1_2_product_service:3003/products/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /categories/ {
            proxy_pass http://lab1_2_product_service:3003/categories/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /orders/ {
            proxy_pass http://lab1_2_orders_service:3006/orders/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /delivery/ {
            proxy_pass http://lab1_2_delivery_service:3004/delivery/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /auth/ {
            proxy_pass http://lab1_2_auth_service:3000/auth/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}